version: '3.3'

services:
  backend:
#    build: ./.
    image: jiyu1948/brave_webtoon:backend
    container_name: backend_blue

    ports:
      - 9002:9002
    environment:
      - HOST=0.0.0.0

  frontend:
#    build: ./frontend
    image: jiyu1948/brave_webtoon:frontend
    container_name: frontend_blue
    ports:
      - 9001:9001
      - 24678:24678
#    volumes:
#      - ./frontend:/frontend
    environment:
      - HOST=0.0.0.0
      - API_URL=http://localhost:9002/ #linux
#      - API_URL=http://host.docker.internal:9002/
    stdin_open: true
    tty: true
    depends_on:
      - backend