version: '3.3'

services:
  backend:
    build: ./.
    container_name: backend_green
    expose:
      - 9003
    ports:
      - 9003:9003
    environment:
      - HOST=0.0.0.0

  frontend:
    build: ./frontend
    container_name: frontend_green
    ports:
      - 9004:9001
      - 24670:24678
    volumes:
      - ./frontend:/frontend
    environment:
      - HOST=0.0.0.0
    stdin_open: true
    tty: true
    depends_on:
      - backend