version: '3.3'

services:
  backend:
    build: ./.
    container_name: backend_blue
    expose:
      - 9002
    ports:
      - 9002:9002
    environment:
      - HOST=0.0.0.0

  frontend:
    build: ./frontend
    container_name: frontend_blue
    ports:
      - 9001:9001
#      - 24678:24678
    volumes:
      - ./frontend:/frontend
    environment:
      - HOST=0.0.0.0
    stdin_open: true
    tty: true
    depends_on:
      - backend