server:
  port : 9002

spring:
  profiles:
    include:
      - db
      - env
  main:
    allow-bean-definition-overriding: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  mybatis:
    configuration:
      map-underscore-to-camel-case:true

  #log4j2
  logging:
    config: classpath:log4j2.xml
    level:
      org:
        springframework:
          security: INFO
        # web: trace
        hibernate:
          SQL: debug
          type: trace
      com:
        amazonaws:
          util:
            EC2MetadataUtils: ERROR

    # change upload file size
    servlet:
      multipart:
        maxFileSize: 10MB # 파일 하나 당 최대 사이즈
        maxRequestSize: 50MB # 요청 당 최대 사이즈

    #devtools reload
    devtools:
      livereload:
        enabled: true
      restart:
        enables: false
    thymeleaf:
      cache: false
      prefix:
        classpath: /templates/

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.example.brave_webtoon
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html            # Swagger UI 경로 => localhost/swagger-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha
    doc-expansion: none
    persist-authorization: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true