server:
  port : 9002

spring:
  profiles:
    include:
      - db

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  mybatis:
    configuration:
      map-underscore-to-camel-case:true

  #log4j2
  logging:
    config: classpath:log4j2.xml
    level:
      org:
        springframework:
          security: INFO
        #          web: trace
        hibernate:
          SQL: debug
          type: trace

    # change upload file size
    servlet:
      multipart:
        maxFileSize: 10MB
        maxRequestSize: 50MB

    #devtools reload
    devtools:
      livereload:
        enabled: true
      restart:
        enables: false
    thymeleaf:
      cache: false
      prefix:
        classpath: /templates/
